apiVersion: v1
kind: Pod
metadata:
  name: avant-pod

spec:
  volumes:
    - name: avant-data
      hostPath:
        path: /var/www/html

  containers:
    - name: avant
      image: gaowanlu/avant:latest
      imagePullPolicy: IfNotPresent

      ports:
        - containerPort: 20023
          name: http
          protocol: TCP
      
      resources:
        requests:
          cpu: "1000m"
          memory: "128Mi"
        limits:
          cpu: "2000m"
          memory: "512Mi"
      
      volumeMounts:
        - name: avant-data
          mountPath: "/avant_static"

      livenessProbe:
        httpGet:
          path: /
          port: 20023
        initialDelaySeconds: 120
        timeoutSeconds: 10
        periodSeconds: 30
        failureThreshold: 5

      readinessProbe:
        httpGet:
          path: /
          port: 20023
        initialDelaySeconds: 120
        timeoutSeconds: 10
        periodSeconds: 30
        failureThreshold: 5
